"""
connectors/lammps/script_builder.py — generate a LAMMPS input script (Step 2.2).

Turns a validated LAMMPSInput into a self-contained `in.lammps` script for an NVT
Lennard-Jones run in reduced units (the canonical melt setup): script-generated fcc lattice,
pair_style lj/cut, fix nvt, thermo output. Pure Python — knows LAMMPS input syntax, runs
nothing.

    <work_dir>/<case_name>/in.lammps

The connector (docs/phase-2.2) invokes `lmp -in in.lammps` from the returned case directory;
LAMMPS writes log.lammps there, which output_parser reads.
"""

from __future__ import annotations

from pathlib import Path

from mcp_server.schemas.lammps import LAMMPSInput

# Fixed RNG seed for velocity initialisation so runs are reproducible (the regression in
# docs/phase-2.2 depends on a deterministic trajectory).
_VELOCITY_SEED = 87287


def render_script(inp: LAMMPSInput) -> str:
    """Render the in.lammps script text from a validated input."""
    nx, ny, nz = inp.lattice.replicate
    temp = inp.ensemble.temperature
    # Thermostat damping: a standard ~100*timestep heuristic for stable NVT control.
    t_damp = 100 * inp.timestep

    return (
        "# LAMMPS input script — generated by Solver-MCP\n"
        f"units           {inp.units.value}\n"
        "atom_style      atomic\n"
        "boundary        p p p\n"
        "\n"
        f"lattice         {inp.lattice.style.value} {inp.lattice.reduced_density}\n"
        f"region          box block 0 {nx} 0 {ny} 0 {nz}\n"
        "create_box      1 box\n"
        "create_atoms    1 box\n"
        "mass            1 1.0\n"
        "\n"
        f"pair_style      lj/cut {inp.potential.cutoff}\n"
        f"pair_coeff      1 1 {inp.potential.epsilon} {inp.potential.sigma}\n"
        "\n"
        f"velocity        all create {temp} {_VELOCITY_SEED}\n"
        f"fix             1 all nvt temp {temp} {temp} {t_damp}\n"
        "\n"
        f"timestep        {inp.timestep}\n"
        f"thermo          {inp.output_frequency}\n"
        "thermo_style    custom step temp press pe ke etotal\n"
        "\n"
        f"run             {inp.n_steps}\n"
    )


def build_script(validated: LAMMPSInput, work_dir: Path) -> Path:
    """Write in.lammps under work_dir/<case_name> and return the case directory."""
    case_dir = Path(work_dir) / validated.case_name
    case_dir.mkdir(parents=True, exist_ok=True)
    (case_dir / "in.lammps").write_text(render_script(validated))
    return case_dir
